apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-operator
  template:
    metadata:
      labels:
        app: edge-operator
    spec:
      serviceAccountName: edge-operator
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: operator
          image: "{{ .Values.operator.image }}"
          imagePullPolicy: IfNotPresent
          command: ["kopf", "run", "/app/src/main.py", "--all-namespaces"]
          ports:
            - containerPort: 8000
              name: metrics

