---
apiVersion: v1
kind: Service
metadata:
  name: edge-operator-metrics
  labels:
    app: edge-operator
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: metrics
  selector:
    app: edge-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edge-operator
  labels:
    app: edge-operator
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: edge-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s